# environment.yml
# This file is for a Conda environment and is recommended for MyBinder.
# It specifies channels and dependencies for a reproducible environment.

name: mybinder-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyter
  - reverse-geocode
  - pyarrow
  - fastparquet
  - geopandas
  - folium
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - shap
  - scipy
  - earthengine-api
  - graphviz
  - python-graphviz
  - pytz
  - ipython
